// src/App.tsx
import React from "react";
import logo from "./images/logo.png";
import "./App.css";

import { Button } from "./components/Button";

declare global {
    interface Window {
        Telegram?: {
            WebApp: any; // 根据实际情况定义 WebApp 的类型
        };
    }
}

function App() {
    function handleProductBtnOnclick(productName: string) {
        if (window.Telegram && window.Telegram.WebApp) {
            const webApp = window.Telegram.WebApp;
            webApp.showAlert(`Buy ${productName}`);
        }
    }

    const products = [
        {
            id: 0,
            name: "Lemon",
        },
        {
            id: 1,
            name: "Melon",
        },
        {
            id: 2,
            name: "Berry",
        },
    ];

    return (
        <div className="flex w-screen flex-col items-center gap-10">
            <img className="w-[200px]" src={logo} alt="logo" />
            <div className=" flex w-full flex-col items-center justify-center gap-5 px-5">
                {products.map((product) => (
                    <div className="flex items-center gap-5" key={product.id}>
                        <img
                            className="w-10 rounded-full"
                            src="https://media.giphy.com/media/VRKheDy4DkBMrQm66p/giphy.gif"
                            alt=""
                        />
                        <Button
                            buttonText={product.name}
                            onClickCallback={() =>
                                handleProductBtnOnclick(product.name)
                            }
                        ></Button>
                    </div>
                ))}
            </div>
        </div>
    );
}

// ******** initialize telegram mini app ********
if (window.Telegram && window.Telegram.WebApp) {
    const webApp = window.Telegram.WebApp;
    console.log(window.Telegram.WebApp);
    webApp.expand();
    webApp.enableClosingConfirmation();
    webApp.BackButton.show();
    webApp.MainButton.show();
    webApp.MainButton.setText("Greeting");
    webApp.onEvent("mainButtonClicked", () => {
        console.log("main button clicked");
        webApp.showAlert("Hi from OCC");
    });
    webApp.onEvent("backButtonClicked", () => {
        console.log("back button clicked");
        webApp.close();
    });
    // set theme colors
    console.log("theme color: ", webApp.themeParams);
} else {
    console.error("Telegram or Telegram.WebApp is not available.");
}

export default App;

// src/App.vue
<template>
    <div
        id="app"
        class="flex h-screen max-h-screen w-screen flex-col justify-between"
    >
        <div class="flex-grow overflow-auto">
            <router-view />
        </div>
        <Navigator v-show="isCurrentRootRoute" class="w-full" />
    </div>
</template>

<script>
import Navigator from "@/components/Navigator.vue";

export default {
    name: "App",
    components: {
        Navigator,
    },
    data: () => ({
        isCurrentRootRoute: true,
    }),
    watch: {
        $route(to, from) {
            console.log("to: ", to);
            console.log("from: ", from);
            // if (to.matched[0] && to.matched[0].name === to.name) {
            //     this.isCurrentRootRoute = true;
            //     window.Telegram.WebApp.BackButton.hide();
            // } else {
            //     this.isCurrentRootRoute = false;
            //     window.Telegram.WebApp.BackButton.show();
            // }
            if (to.name !== "matches") {
                window.Telegram.WebApp.BackButton.show();
            } else {
                window.Telegram.WebApp.BackButton.hide();
            }
        },
    },
    methods: {
        handleTelegramBackBtnClicked() {
            window.Telegram.WebApp.onEvent("backButtonClicked", () => {
                console.log("back button clicked");
                // this.$router.push({ name: this.$route.matched[0].name });
                this.$router.push({ name: "index" });
            });
        },
        tgInit() {
            if (window.Telegram && window.Telegram.WebApp) {
                const webApp = window.Telegram.WebApp;
                console.log(window.Telegram.WebApp);
                webApp.expand();
                webApp.enableClosingConfirmation();
                // set theme colors
                console.log("theme color: ", webApp.themeParams);
                // webApp.showAlert("Hi from OCC");
                webApp.showPopup({
                    title: "popup",
                    message: "message",
                    buttons: [
                        {
                            type: "close",
                            text: "text",
                        },
                    ],
                });
                // webApp.showConfirm("confirm now?", () => {
                //     webApp.showAlert("CONFIRM");
                // });
            } else {
                console.error("Telegram or Telegram.WebApp is not available.");
            }
        },
    },
    created() {
        this.tgInit();
        this.handleTelegramBackBtnClicked();
    },
};
</script>
